/**
 * Saflı Akrilik Cami Halısı Desen Verileri
 * 17 farklı desen — renk değiştirme ve galeri bileşenleriyle kullanılır
 */

export interface SafliAkrilikDesen {
  id: string;
  slug: string;
  image: string;
  name: string;
  nameEn: string;
  nameAr: string;
  /** Desendeki baskın renkler — renk değiştirme simülatöründe kullanılır */
  dominantColors: string[];
  altText: string;
  altTextEn: string;
  altTextAr: string;
}

export const SAFLI_AKRILIK_DESENLER: SafliAkrilikDesen[] = [
  {
    id: "safli-akrilik-01",
    slug: "safli-akrilik-desen-01",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-01.webp",
    name: "Yıldız Geometri",
    nameEn: "Star Geometry",
    nameAr: "هندسة النجوم",
    dominantColors: ["#006B7B", "#4CC4C4", "#FFFFFF"],
    altText: "Saflı akrilik cami halısı yıldız geometri deseni",
    altTextEn: "Acrylic mosque carpet star geometry pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط النجوم الهندسي",
  },
  {
    id: "safli-akrilik-02",
    slug: "safli-akrilik-desen-02",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-02.webp",
    name: "Sade Bordür",
    nameEn: "Simple Border",
    nameAr: "حدود بسيطة",
    dominantColors: ["#0097A7", "#005566", "#E0F0F0"],
    altText: "Saflı akrilik cami halısı sade bordür deseni",
    altTextEn: "Acrylic mosque carpet simple border pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الحدود البسيطة",
  },
  {
    id: "safli-akrilik-03",
    slug: "safli-akrilik-desen-03",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-03.webp",
    name: "Osmanlı Motif",
    nameEn: "Ottoman Motif",
    nameAr: "زخرفة عثمانية",
    dominantColors: ["#006B7B", "#4CC4C4", "#C9972B"],
    altText: "Saflı akrilik cami halısı Osmanlı motif deseni",
    altTextEn: "Acrylic mosque carpet Ottoman motif pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الزخرفة العثمانية",
  },
  {
    id: "safli-akrilik-04",
    slug: "safli-akrilik-desen-04",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-04.webp",
    name: "Klasik Saflı",
    nameEn: "Classic Lined",
    nameAr: "صفوف كلاسيكية",
    dominantColors: ["#006B7B", "#4CC4C4", "#E0C880"],
    altText: "Saflı akrilik cami halısı klasik saflı desen",
    altTextEn: "Acrylic mosque carpet classic lined pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الصفوف الكلاسيكية",
  },
  {
    id: "safli-akrilik-05",
    slug: "safli-akrilik-desen-05",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-05.webp",
    name: "Lale Motif",
    nameEn: "Tulip Motif",
    nameAr: "زخرفة الزنبق",
    dominantColors: ["#0097A7", "#002244", "#E0C880"],
    altText: "Saflı akrilik cami halısı lale motif deseni",
    altTextEn: "Acrylic mosque carpet tulip motif pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الزنبق",
  },
  {
    id: "safli-akrilik-06",
    slug: "safli-akrilik-desen-06",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-06.webp",
    name: "İnce Çizgi",
    nameEn: "Fine Line",
    nameAr: "خطوط رفيعة",
    dominantColors: ["#006B7B", "#3BB8B8", "#002244"],
    altText: "Saflı akrilik cami halısı ince çizgi deseni",
    altTextEn: "Acrylic mosque carpet fine line pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الخطوط الرفيعة",
  },
  {
    id: "safli-akrilik-07",
    slug: "safli-akrilik-desen-07",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-07.webp",
    name: "Selçuklu Yıldız",
    nameEn: "Seljuk Star",
    nameAr: "نجمة سلجوقية",
    dominantColors: ["#006B7B", "#4CC4C4", "#C9972B"],
    altText: "Saflı akrilik cami halısı Selçuklu yıldız deseni",
    altTextEn: "Acrylic mosque carpet Seljuk star pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط النجمة السلجوقية",
  },
  {
    id: "safli-akrilik-08",
    slug: "safli-akrilik-desen-08",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-08.webp",
    name: "Mihrap Bordür",
    nameEn: "Mihrab Border",
    nameAr: "محراب مزخرف",
    dominantColors: ["#006B7B", "#3BB8B8", "#E0C880"],
    altText: "Saflı akrilik cami halısı mihrap bordür deseni",
    altTextEn: "Acrylic mosque carpet mihrab border pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط المحراب المزخرف",
  },
  {
    id: "safli-akrilik-09",
    slug: "safli-akrilik-desen-09",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-09.webp",
    name: "Geometrik Şerit",
    nameEn: "Geometric Strip",
    nameAr: "شريط هندسي",
    dominantColors: ["#006B7B", "#4CC4C4", "#002244"],
    altText: "Saflı akrilik cami halısı geometrik şerit deseni",
    altTextEn: "Acrylic mosque carpet geometric strip pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الشريط الهندسي",
  },
  {
    id: "safli-akrilik-10",
    slug: "safli-akrilik-desen-10",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-10.webp",
    name: "Dokuma Doku",
    nameEn: "Woven Texture",
    nameAr: "نسيج محاك",
    dominantColors: ["#005566", "#3BB8B8", "#002244"],
    altText: "Saflı akrilik cami halısı dokuma doku deseni",
    altTextEn: "Acrylic mosque carpet woven texture pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط النسيج المحاك",
  },
  {
    id: "safli-akrilik-11",
    slug: "safli-akrilik-desen-11",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-11.webp",
    name: "Çiçek Motif",
    nameEn: "Floral Motif",
    nameAr: "زخرفة زهرية",
    dominantColors: ["#006B7B", "#4CC4C4", "#C9972B"],
    altText: "Saflı akrilik cami halısı çiçek motif deseni",
    altTextEn: "Acrylic mosque carpet floral motif pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الزخرفة الزهرية",
  },
  {
    id: "safli-akrilik-12",
    slug: "safli-akrilik-desen-12",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-12.webp",
    name: "Modern Saflı",
    nameEn: "Modern Lined",
    nameAr: "صفوف عصرية",
    dominantColors: ["#0097A7", "#005566", "#E0F0F0"],
    altText: "Saflı akrilik cami halısı modern saflı desen",
    altTextEn: "Acrylic mosque carpet modern lined pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الصفوف العصرية",
  },
  {
    id: "safli-akrilik-13",
    slug: "safli-akrilik-desen-13",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-13.webp",
    name: "Halı Bordür",
    nameEn: "Carpet Border",
    nameAr: "حدود السجاد",
    dominantColors: ["#006B7B", "#4CC4C4", "#C9972B"],
    altText: "Saflı akrilik cami halısı halı bordür deseni",
    altTextEn: "Acrylic mosque carpet border pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط حدود السجاد",
  },
  {
    id: "safli-akrilik-14",
    slug: "safli-akrilik-desen-14",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-14.webp",
    name: "Zincir Motif",
    nameEn: "Chain Motif",
    nameAr: "زخرفة السلسلة",
    dominantColors: ["#006B7B", "#3BB8B8", "#E0C880"],
    altText: "Saflı akrilik cami halısı zincir motif deseni",
    altTextEn: "Acrylic mosque carpet chain motif pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط السلسلة",
  },
  {
    id: "safli-akrilik-15",
    slug: "safli-akrilik-desen-15",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-15.webp",
    name: "Büyük Yıldız",
    nameEn: "Large Star",
    nameAr: "نجمة كبيرة",
    dominantColors: ["#005566", "#4CC4C4", "#002244"],
    altText: "Saflı akrilik cami halısı büyük yıldız deseni",
    altTextEn: "Acrylic mosque carpet large star pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط النجمة الكبيرة",
  },
  {
    id: "safli-akrilik-16",
    slug: "safli-akrilik-desen-16",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-16.webp",
    name: "Arabesque",
    nameEn: "Arabesque",
    nameAr: "أرابيسك",
    dominantColors: ["#006B7B", "#4CC4C4", "#C9972B"],
    altText: "Saflı akrilik cami halısı arabesque deseni",
    altTextEn: "Acrylic mosque carpet arabesque pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الأرابيسك",
  },
  {
    id: "safli-akrilik-17",
    slug: "safli-akrilik-desen-17",
    image: "/images/desenler/safli-akrilik/safli-akrilik-desen-17.webp",
    name: "Minimal Saflı",
    nameEn: "Minimal Lined",
    nameAr: "صفوف بسيطة",
    dominantColors: ["#005566", "#0097A7", "#002244"],
    altText: "Saflı akrilik cami halısı minimal saflı desen",
    altTextEn: "Acrylic mosque carpet minimal lined pattern",
    altTextAr: "سجاد مسجد أكريليك بنمط الصفوف البسيطة",
  },
];
