-- ================================================================
-- camiihalisi.com — Şehir & Keyword Seed SQL
-- Supabase SQL Editor'e yapıştırın → Run
-- 302 keyword sayfası, 78 şehir
-- ================================================================

-- ADIM 1: Şehir kayıtları (varsa atla)
INSERT INTO "City" (id, slug, name, type, "isActive", "createdAt", "updatedAt")
VALUES
  ('cUucXA3MrN3i8z7sB114MOeY1', 'adana', 'Adana', 'il', true, NOW(), NOW()),
  ('cAUowNLmDpIo8LcKPydWjHgh2', 'afyonkarahisar', 'Afyonkarahisar', 'il', true, NOW(), NOW()),
  ('cbtqCFicklw7wH5HRV5oA2OZ9', 'agri', 'Ağrı', 'il', true, NOW(), NOW()),
  ('crKCekEihcu1TNZI9BIKJ3x4N', 'aksaray', 'Aksaray', 'il', true, NOW(), NOW()),
  ('cdvQgfd08pCsrutXGHmNjAA7n', 'amasya', 'Amasya', 'il', true, NOW(), NOW()),
  ('cRt37JP856mY9MK5CODmhjLfb', 'ankara', 'Ankara', 'il', true, NOW(), NOW()),
  ('clrxtmUbOWFKep6gSBbFojBWF', 'antalya', 'Antalya', 'il', true, NOW(), NOW()),
  ('cFXhP83TJow3R0BREojsoSOHN', 'ardahan', 'Ardahan', 'il', true, NOW(), NOW()),
  ('cAvRmy5uxNDuu1ARb75gapueG', 'artvin', 'Artvin', 'il', true, NOW(), NOW()),
  ('cCajCluUEKUuUBwESpTcYyKRn', 'aydin', 'Aydın', 'il', true, NOW(), NOW()),
  ('chjlJ7jKpcfaymN1UeXZ6SM23', 'balikesir', 'Balıkesir', 'il', true, NOW(), NOW()),
  ('c0tF98UaBmWRNLdROcEUHi3Ng', 'bartin', 'Bartın', 'il', true, NOW(), NOW()),
  ('cpvfmpybOYvNLjqGS0rnR8txA', 'batman', 'Batman', 'il', true, NOW(), NOW()),
  ('cOQBepzITYGTEyaOyXquWuK3i', 'bayburt', 'Bayburt', 'il', true, NOW(), NOW()),
  ('c8z80QdtcNvOF1k3fEpO37coV', 'bilecik', 'Bilecik', 'il', true, NOW(), NOW()),
  ('cUVuvgiv9okeQfOXtF6sr0qRr', 'bingol', 'Bingöl', 'il', true, NOW(), NOW()),
  ('c5zSZcBqrmRMfNTXsUlWnBwBY', 'bitlis', 'Bitlis', 'il', true, NOW(), NOW()),
  ('c91yatAkwBx4ogmqS5W10YZNh', 'bolu', 'Bolu', 'il', true, NOW(), NOW()),
  ('ct7WaiioqgMmtw3fQReLCv5wj', 'burdur', 'Burdur', 'il', true, NOW(), NOW()),
  ('cC7wC8NupcacBhUMQ7W96vxpZ', 'bursa', 'Bursa', 'il', true, NOW(), NOW()),
  ('cUPl6RV15kYASzcHGXvtt8s76', 'canakkale', 'Çanakkale', 'il', true, NOW(), NOW()),
  ('cClomRDJw0cGsSaUcHzer7GPZ', 'corum', 'Çorum', 'il', true, NOW(), NOW()),
  ('cS7FhKMkNWYHbkfzaoGxHRj68', 'denizli', 'Denizli', 'il', true, NOW(), NOW()),
  ('c1VCJWBYkI2yKawDBYkWPtnvR', 'diyarbakir', 'Diyarbakır', 'il', true, NOW(), NOW()),
  ('cX9Hyg33S3OapdkIY9uVJnBJx', 'duzce', 'Düzce', 'il', true, NOW(), NOW()),
  ('cRRrvWPNvnNqAEs78UsfSrpeP', 'edirne', 'Edirne', 'il', true, NOW(), NOW()),
  ('c5e3RnOTsB6IY7A05IqGnSGhQ', 'elazig', 'Elazığ', 'il', true, NOW(), NOW()),
  ('cc0f3IklDhbeblz9GtCvddlg1', 'erzincan', 'Erzincan', 'il', true, NOW(), NOW()),
  ('cdtmSnoigerZOP83HwzPZU6bj', 'erzurum', 'Erzurum', 'il', true, NOW(), NOW()),
  ('cBHIEdo6L0Hn6BVUFnY5DD4Ie', 'eskisehir', 'Eskişehir', 'il', true, NOW(), NOW()),
  ('cnGlb2mwiotmDQBHV1Ckny8n2', 'gaziantep', 'Gaziantep', 'il', true, NOW(), NOW()),
  ('cZOXjz6lHrbxPd4rac90IaqhS', 'giresun', 'Giresun', 'il', true, NOW(), NOW()),
  ('c5ctVAz9ByH6Ib9Qj1Z20ukmc', 'gumushane', 'Gümüşhane', 'il', true, NOW(), NOW()),
  ('cSPU7HJ09Rr8VUoIze5sXQ37X', 'hakkari', 'Hakkari', 'il', true, NOW(), NOW()),
  ('c9mXqN5moOpDGVIXfi3LKCyY9', 'hatay', 'Hatay', 'il', true, NOW(), NOW()),
  ('cGycBqZJd3Ov8lqGEwH01vZBa', 'igdir', 'Iğdır', 'il', true, NOW(), NOW()),
  ('cV943yU5TzeA64rN5HsvhzZ7V', 'isparta', 'Isparta', 'il', true, NOW(), NOW()),
  ('cEBr2t3CP5rowGiC29MCS4H8s', 'istanbul', 'İstanbul', 'il', true, NOW(), NOW()),
  ('cJF28L3yi2NoywqHyFQVcSYpx', 'izmir', 'İzmir', 'il', true, NOW(), NOW()),
  ('cLaFCphfDwL4IjPkh0dSIEYsL', 'kahramanmaras', 'Kahramanmaraş', 'il', true, NOW(), NOW()),
  ('cHkK2TTocEX1u7XeKMbOlsqnf', 'karabuk', 'Karabük', 'il', true, NOW(), NOW()),
  ('cEKsx8WwdgmAE4WQ268NCFKBG', 'karaman', 'Karaman', 'il', true, NOW(), NOW()),
  ('cbAxrinEat4PHpMxCn6ilovHO', 'kars', 'Kars', 'il', true, NOW(), NOW()),
  ('cNeH47cxLoPNwpihDo1mPlCCh', 'kastamonu', 'Kastamonu', 'il', true, NOW(), NOW()),
  ('cwoYyuhN2iK1pp9KYQPXrTHit', 'kayseri', 'Kayseri', 'il', true, NOW(), NOW()),
  ('ch9uKxXMyXqJ9xJHkgi5Ikgsw', 'kilis', 'Kilis', 'il', true, NOW(), NOW()),
  ('cfmHKejau4hMYwthGVmyqVUj0', 'kirikkale', 'Kırıkkale', 'il', true, NOW(), NOW()),
  ('c8U8NGHB5A5c6cdRB6N8xpK5t', 'kirklareli', 'Kırklareli', 'il', true, NOW(), NOW()),
  ('cz76HW8sOqy8UMJIXaJT5ikyS', 'kirsehir', 'Kırşehir', 'il', true, NOW(), NOW()),
  ('c8IVJqSnXVqB2tD7t0lM7PLDC', 'kocaeli', 'Kocaeli', 'il', true, NOW(), NOW()),
  ('ce3D9bQ9QOYR8AsQrnCIvZBQP', 'konya', 'Konya', 'il', true, NOW(), NOW()),
  ('cMDTn92ipuG8YZvPvJBtlLJz5', 'kutahya', 'Kütahya', 'il', true, NOW(), NOW()),
  ('cu3aq1Of2km4Ap2lx3iw5bb5A', 'malatya', 'Malatya', 'il', true, NOW(), NOW()),
  ('clDNW2FFk4AhiQN2E3QntviIp', 'manisa', 'Manisa', 'il', true, NOW(), NOW()),
  ('ckhWx4zv0Vqbfh904QY6lJ0DW', 'mardin', 'Mardin', 'il', true, NOW(), NOW()),
  ('cc19dtT4vo1MyskMoIEm0wLgr', 'mersin', 'Mersin', 'il', true, NOW(), NOW()),
  ('cS4J4ZSXycC7f7mIU3t8V5rFB', 'mugla', 'Muğla', 'il', true, NOW(), NOW()),
  ('cVN1pqnTPHLdZrpH8ZbQ6f9OP', 'mus', 'Muş', 'il', true, NOW(), NOW()),
  ('cF9WgkvaqEqjAzwWdUrSIlp3S', 'nevsehir', 'Nevşehir', 'il', true, NOW(), NOW()),
  ('cjVw2xLHjgb2oG3UwcNuZQjy0', 'nigde', 'Niğde', 'il', true, NOW(), NOW()),
  ('cL36zKYFTwxiRPEu69xSgX6tW', 'ordu', 'Ordu', 'il', true, NOW(), NOW()),
  ('cIARYYYy3drTNCh9vPf8FiwyB', 'osmaniye', 'Osmaniye', 'il', true, NOW(), NOW()),
  ('capLpVoXTrPumGDZpJ6Vgl0Q9', 'rize', 'Rize', 'il', true, NOW(), NOW()),
  ('cPR6WRHRIwMOAynW8yKif9LPJ', 'sakarya', 'Sakarya', 'il', true, NOW(), NOW()),
  ('cbTzuIIUgyOB5FTATI8xqulh4', 'samsun', 'Samsun', 'il', true, NOW(), NOW()),
  ('cPJjXSYda0CVBea8dYP7NCfRC', 'sanliurfa', 'Şanlıurfa', 'il', true, NOW(), NOW()),
  ('cEZ7JYBUbjUSSI0Ng3LMwHH6k', 'siirt', 'Siirt', 'il', true, NOW(), NOW()),
  ('c3UHMkGyi7DoPUL8n0XTlRVdt', 'sinop', 'Sinop', 'il', true, NOW(), NOW()),
  ('cpv0pRNuQ8ez3jWlQGvEB4Vy4', 'sirnak', 'Şırnak', 'il', true, NOW(), NOW()),
  ('cotiaGaXhjBaMPg5HFwk5EYDS', 'sivas', 'Sivas', 'il', true, NOW(), NOW()),
  ('cLNUrLolDl0h0AjBmwJVdSP5B', 'tekirdag', 'Tekirdağ', 'il', true, NOW(), NOW()),
  ('ce7sYaZiYAiC1mb9SVqJFT4DT', 'tokat', 'Tokat', 'il', true, NOW(), NOW()),
  ('cLHumAWTuitqT16GDxjAlEGI4', 'trabzon', 'Trabzon', 'il', true, NOW(), NOW()),
  ('cozCVcxXztFw5wD8mWNkjW8jl', 'tunceli', 'Tunceli', 'il', true, NOW(), NOW()),
  ('ceLqGJpVLZGNtIB2fuQePtbnH', 'usak', 'Uşak', 'il', true, NOW(), NOW()),
  ('cRn50OTmF4nb2Mr5osP89b6E5', 'van', 'Van', 'il', true, NOW(), NOW()),
  ('cbIeFQQPGXNiR4VVWMcYJkFRL', 'yozgat', 'Yozgat', 'il', true, NOW(), NOW()),
  ('c06mKowyMKYH0ePmhSvh6Pi7D', 'zonguldak', 'Zonguldak', 'il', true, NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

-- ADIM 2: Şehir × Keyword kombinasyonları
INSERT INTO "CityKeyword" (id, "citySlug", keyword, "keywordSlug", "isActive", "createdAt", "updatedAt")
VALUES
  ('cPkVyAKDMqgFyZWGYE4lX1U4f', 'istanbul', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cS2pnPHuTrqkyBhsnIWxrXQsf', 'istanbul', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c9Ha40hvmx5FpGOMycdyeSzva', 'istanbul', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cOahPW5rxsU1gc9TXgncZ99fa', 'istanbul', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cD97TlsPddQqfxE5cNlFnBNX3', 'istanbul', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cKKrnE7SAejzklnDFaj5uAjMa', 'istanbul', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c4mKu5p7Ifa7Ly4DyCbTVwXWt', 'ankara', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cArhcBHBXXuoCEHGE3FW5jvU0', 'ankara', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cY2JnrbO7m7OdnAhEOhkVgSJM', 'ankara', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cb68aPlk6vDbO3DErwgOPc5rn', 'ankara', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c5LfG6xEdnomyT2gP6v8Vn6E1', 'ankara', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('chqlz87EogXXfH76aNYV2Xgjx', 'ankara', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cWCXKETGzlIwAmxtso0LebuNI', 'izmir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cZChDgnzLzOblCH762ebFwhjR', 'izmir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cPgqoxHU5FpEaiX0CFO5o5WTO', 'izmir', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c552wgDi34mMM7eOTc9aqK6lg', 'izmir', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('czFRDxQUOGYi6JfJRfZrJQM7C', 'izmir', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cN1a8z1HYbljGH47jMxup22ct', 'izmir', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cLP7VQjGBTcQW7laKh3JiQ2vA', 'bursa', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c2kwOZap6ZhpbC0nwsljrli41', 'bursa', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cR1d5HC4t6Sp12JmcgCTeMgBu', 'bursa', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cjf1Yk5GenhOGXopICevluCVB', 'bursa', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cjrfUAN9P4neLLwkujK1h1exu', 'bursa', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('ciIbLE3wI06Ls7r9QPz57Wv18', 'bursa', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cG9d2BPGmSLNKCCDzEZNCzaph', 'antalya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('czpFyHr1jlSin3ubERbNl33Us', 'antalya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cUsKehdF0B26QGsNDTVPwgmYR', 'antalya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cZHln3NZdSbUW2HOtOrhkCh4v', 'antalya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cD3dsMKEglIuGV5t5kFDHI3PD', 'antalya', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('csKFSfwvRLOf6SPCdx3Z03R8E', 'antalya', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c06vdZUb6AddUkXVg9lSkPk6W', 'konya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c6E2bsdnkT4IZ28sJE9yClgDH', 'konya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c4kihjM3NlgupgLCPeXsaNnhA', 'konya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c50NwCd1BIH1KZRMBDc42JaJj', 'konya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('copLahTN93LZeTz4Fv1L9OGW7', 'konya', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cZcybOeISP79XOSutFKmvwpUA', 'konya', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cVrzphXCOelfZL5GDff3cQO55', 'kayseri', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cKW3yiHZfJOwA6V90MynSBG8i', 'kayseri', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c32LmfnH5E0EmYkoUHev4t4kD', 'kayseri', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cJPLfxULx35G7zpv4147rFWyI', 'kayseri', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cKhLe2lJgaXm7eadyyhEGXibM', 'kayseri', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('caJwIJcJ2WJv9swnprhHnimek', 'kayseri', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c8VmX2KgHrQyfBPDaR30IzurI', 'adana', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c6FhHdx2k5EBvouNH05MYrQDX', 'adana', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c46It62DDjwWgc3oXti3IjYcZ', 'adana', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cKYQ6r4BffZ8EOJm65A1cfIaz', 'adana', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cMAieqqsrCJDwODZi6B61F8Wi', 'adana', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('couStrhAl0yIxbumtoCtlrMLH', 'adana', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cFADYryt11DEqLwXIGhiCJE9m', 'gaziantep', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cjoNZROJ1FAEgSRbV36rtCRWd', 'gaziantep', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cZhlhP3wYuOtb7rHL4ilKezaZ', 'gaziantep', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cqZKVlrZKVTmG5V3EEC7UOEUU', 'gaziantep', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c7Zus9ffhGE38KVGZltAXopJf', 'gaziantep', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cGBwcRZ024fJCPcZcbdc88bX3', 'gaziantep', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c3cHQa94HsMsxaM46jjsLhH8R', 'mersin', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('chMVRDrUrNoLygpva80CB4M4T', 'mersin', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cNehexucn5sQUExLSvOkj9Y8v', 'mersin', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cAex0msfQb4WxD1EN8gPqhRDu', 'mersin', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cUg9iMFUt4C8Vf7XaUhD1ZpNT', 'mersin', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cdsCM1mBh4QX4snA0Gr63kctZ', 'mersin', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('ct2j76gklX2WfI26IOhM9wBul', 'kocaeli', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ca8o4gQ9TGpDOnNnCzE7KKVOg', 'kocaeli', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cch4XBHloq8DXvYeRYRlHpagM', 'kocaeli', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cUMn0gi7vkUV1iQhR0XsdS6vb', 'kocaeli', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c2fmoj8epxNLYi0hCN4oExubF', 'kocaeli', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cMNsfsWN5rFaTfjkJ6eDzvAXE', 'kocaeli', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cqmny7fjIEduzuRWOpBmXEoip', 'diyarbakir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cdYXMUSFO8vVSCI84ESLwIRir', 'diyarbakir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cMtwnzkYsjnXfFPw9h7YrU34m', 'diyarbakir', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cdpftKni8nlet8GFPv3PqoQzu', 'diyarbakir', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cH94PoIo4xRYgwul2gjOwcJCP', 'diyarbakir', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cPRUDQAOExQB2juHcRmGoTlj0', 'diyarbakir', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cxfmBQ2ezdapNI0AN7TF6olcQ', 'samsun', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cmlad67jlX9F9iT0FF1Eqjbjv', 'samsun', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cKwcZuYaJJw06fJoD97bhai8y', 'samsun', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cCRXiftd2zM6dl36l15nyYpKY', 'samsun', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cyyeoGzSjDysqTESpZdOgq2zr', 'samsun', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cVsbwpssDgJqpxhQ6RPCheXhe', 'samsun', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c5J612lkDFrUUCqrVxdLSWBo8', 'eskisehir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cnJi7kCbq7tB02hRy9qqOmhNA', 'eskisehir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('czBMtI5PJJkG67v5F2PZXoFEv', 'eskisehir', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cU2GKYnXwKQ2Y22RRyYW9wvcP', 'eskisehir', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('covwEqf2P1tDr8XZmYpZfgLys', 'eskisehir', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cgmPjQG2pbK55FsJuIJkR15b0', 'eskisehir', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cDnqH83s90jLgEgiYMNYT9kp2', 'trabzon', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cedWFQpgxP4liAkZciNP7AwLo', 'trabzon', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c6wLIhKjDCfRj9Mi5Zn8Wkg49', 'trabzon', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cflrtI2fqVton01IvCKD4J6GB', 'trabzon', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cD4rusrJJZ3YWYW8O2bR7W2HN', 'trabzon', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('c1YYWtUttAlBPcXxqDUsjykHw', 'trabzon', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cCAwkh48pmzndfZI1GlaWajpG', 'sanliurfa', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c7QOO3ELww3PVt4WZh0zPmeiO', 'sanliurfa', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cBxM6EhTpwxxZ1ug1EvPl0h9C', 'sanliurfa', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c00NvxjQIVgXIVXJsyd8gYYIg', 'sanliurfa', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cSSE5KB3GwlmDor3VefILEQdX', 'sanliurfa', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cD4Hwx3NG1Wa0H72BJdcNpbS4', 'sanliurfa', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c78mTSZ5yy8bgvmRROSoGQNGk', 'hatay', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cInGO90raanZnV5VdMP69S7Jf', 'hatay', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('ccXABfkFCagWkGP87aL2Ephma', 'hatay', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c8fIqHLVsfxyp627guxDCMBia', 'hatay', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('czQEXJFRN5PldmPdRi8r4fcUR', 'hatay', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cQPqWbXIygpRBGbiD4slMg05N', 'hatay', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cunM86pfoPUNF70SLamAG7bFA', 'manisa', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cSHIBmwSgkfAyyjNlBjf6d30W', 'manisa', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c7uiOOzMHXrUtvD8xQESVIAl9', 'manisa', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c6iMajSoazvYrvgu6UOnYpSB9', 'manisa', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cx7GGEwpiHMIFN9hNSHyaghCF', 'manisa', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('c8PQrFPtM49sYrTBsgoyNutCx', 'manisa', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('c3uFMlnzSM5bYwMyVOChlh1p6', 'tekirdag', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c7ib7zk0fZdmR4MM075n3ovYN', 'tekirdag', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cnu9AeT1G1t469o47UIulxoqB', 'tekirdag', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cgvS6cYc2bWK4Ty5z9aq7k6VQ', 'tekirdag', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cmN7CwM9amw21EXBOrRtd2HsG', 'tekirdag', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cTpRQ4XHwFwZQCVI9QfiZX2aO', 'tekirdag', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cDOb3JIJaIOSxUPkMU6BmqHrq', 'malatya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cbrP9T6DgZlMfyVpVjKNwdANA', 'malatya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c8dNJkeQqnWVSxLsrekQQmIzM', 'malatya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cIDD0v0o4um3BVrubef0tf9JW', 'malatya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cywbAZOymX2wtBAjIbxIp0OsZ', 'malatya', 'Cami Halısı Fiyatları', 'cami-halisi-fiyatlari', true, NOW(), NOW()),
  ('cEXmtpFDHMT6SQketOhFYXx0c', 'malatya', 'Özel Desen Cami Halısı', 'ozel-desen-cami-halisi', true, NOW(), NOW()),
  ('cHmaou53QnPwjRyvnB2xfft91', 'balikesir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('coPoG8sNx35S2fXaiBOpk9PuF', 'balikesir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cXpuCSOEJD9v2rQuS8m1vPeam', 'balikesir', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cehzmJEoUWa2BMgwkgAwQay0E', 'balikesir', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cXmGBrQcwp7PvHvB3YRWIP8X8', 'aydin', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cdKSLYL5DD56RkPmnq4UQheWL', 'aydin', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cEl2RLzterxmSlTQaoOT2OiHF', 'aydin', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('caQ0VimR5ZIVob7npm2A6EOM5', 'aydin', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cK2lTN9mtnoay4V8di383BfoL', 'kahramanmaras', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cYtQBATWsHsAV5GAc2npCRk0B', 'kahramanmaras', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cPPKtDAd5N4TkMb3UsViXzkin', 'kahramanmaras', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cJp1DM8nAlUeQ642nAMbFwVfF', 'kahramanmaras', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cv0SVNjqBsCetePfKcYARGfqS', 'sakarya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c2yxJYwUz6A8rHXQDLnxPrBFJ', 'sakarya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cH5OS1njMhoWa0RkvgYwmBYr2', 'sakarya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('ctWDYwABVjodaGdWzwixVveNu', 'sakarya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c975NBpLoZkbqadeCgjGPcp50', 'mugla', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c3cphdKIo8osmRMhUHwJEDgjX', 'mugla', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cnMUgpqQDwit2qDvtIU7F9lro', 'mugla', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c4uvlyW43BsxPFRXTI7Cy76dE', 'mugla', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c67XHDEgYIlZ2ctyZbktdVbdb', 'van', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c9GVKgJxHwsdbvCCmhJTve0C4', 'van', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c94mmnVdqTWsLIVgWlk27sZYb', 'van', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cpfsFhr0aPo5q8EGaLxGhE6S9', 'van', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('chmGD6t6bUuyxDaMk0ymngkjz', 'erzurum', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cSvXmNKDkWEEQC4HxFnmV5NwS', 'erzurum', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cQZsMb5feEY4v8RnUbYUim7iF', 'erzurum', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cJ0KHxvlhHEF1EcLLhl3x7BFQ', 'erzurum', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cPZCCjk1bK9NkYlQDEf4XaCwS', 'afyonkarahisar', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cLGhsEz6fWSRjp9oFp8QYYAOI', 'afyonkarahisar', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cl9J9bF3cqhGRn6DSzEaDcuNN', 'afyonkarahisar', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cOWPcttBTOiVkHOEepeFHYKnA', 'afyonkarahisar', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cod9sxGyIRqtvu1NrlJCDRPXC', 'kutahya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c9xC5JB1IT7LBhJksioSLnDts', 'kutahya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cdZ2pRno3hG5mqpZ3bnp1Ounw', 'kutahya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c7y994K4kee3wkyyK8gOZbV8c', 'kutahya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('czDmAl0rKi7OTelZJ6z6mJRn9', 'sivas', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('coOk38L3Vic3PfQdicECzQkyO', 'sivas', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c9ynaeqRrNuyAng6x6C7PVbPe', 'sivas', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cQzZ82OlwBfQGoa3PqUhhJCAN', 'sivas', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cxCR0aYliQWbl7tapnkjONtgm', 'zonguldak', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cQ0UoMHmfHKWIzFsV6hEZbvXZ', 'zonguldak', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('ckAN6ZzBYf100xVZ126a0FCWB', 'zonguldak', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cmWJDxyaZhmOCucils7wf23V7', 'zonguldak', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cSnrojYDD5xFs41UVrP9zvIlL', 'bolu', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cHUfVgUCMBrLXmbIKvwlqIIuE', 'bolu', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cr4jPId0gbSKMvKe1qVbO9KrO', 'bolu', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('ceU2CL3cK4LWYZLJvYL60MOBD', 'bolu', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cYagQjwam7TsVe4mA6ykuTRZ5', 'canakkale', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cizVOFQS9yTGkzqZ63AFwnTE7', 'canakkale', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cWRE6qZrnWj3ddqtYBfpjuFMo', 'canakkale', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cQsNe1UVAyzexYunrljUnUFnN', 'canakkale', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c0him80yFZ49eyNMhYqBopXyF', 'isparta', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('csV7WcbtxU0xFpgqbnhBcNsAh', 'isparta', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cT76olqz341oyfIWAzcGL6Xsv', 'isparta', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cOHhAZ1hLBpakobvICXA3PwSS', 'isparta', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('ce7GLyR2UHoPOkgOqzy3zoFAo', 'kirklareli', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('caoiGhEULI9DQG1fCm2fW7GaV', 'kirklareli', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cTGd9wWZo7T2G41UZmgYW2Hhi', 'kirklareli', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cFjlxl45236neqlnWB1OzGK7G', 'kirklareli', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('ckMGZ1DsuQlFILtHpnScYESGk', 'edirne', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cSEJEX3XTPYUigIoH4JvO2cj5', 'edirne', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('ckawUr3kcD3HUdB4fCMYiR8Ze', 'edirne', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cvyc1oj7zwuTOSAVEKBqaUXXp', 'edirne', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cx52M9N5IUBjyplu6VNysi2fH', 'kirikkale', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cr2NEPwP5G7tA1pou8I6dLmW1', 'kirikkale', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cfo9kWXRhnt1uW6hpP7eE4Cag', 'kirikkale', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cJHQwkQ4th8JRApjlPNSKOi1b', 'kirikkale', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c5aVKxOCkJRBpZJhEp9y3FneJ', 'ordu', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cb5CAlXDDGjwkcEfITAhJYtVS', 'ordu', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('csNf6F9mKJ2kWsGTOwGDvfGa6', 'ordu', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c8YAPFIB0vvQef9r7JsHZMjhT', 'ordu', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cfMCONWKGYPn6YjD2UPyncmeJ', 'giresun', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cVQmiZfgYXPEYTuvNyvND6UbC', 'giresun', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('caoFDZkXcqBCtkH9glEZW4ZGQ', 'giresun', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c8xSzPdMKKCO7fXK8ixJVNIpI', 'giresun', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cMMVOBM6bSTVcOrlxfcM1sdua', 'rize', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cvYEEXbEk4MP5zsS1yDEkFmCM', 'rize', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cBYEOm8scSOkTZCmgLVLvXGYm', 'rize', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c9kamSJ7g6BxN9xvZFcGWtt8V', 'rize', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cqQNCIQ2vKMSjk49psW7Pt1AC', 'artvin', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cE6ZTHfw9sdeTdiSPCW71Uj9V', 'artvin', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c9fXkuHDbgyhdcsqOQDxnSHtc', 'artvin', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('crZjgWMGsF5dDBD0JWR23hPZh', 'artvin', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cuNNlrviz3qfUIYI94vutzdyW', 'kastamonu', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('czS2l78UPOcut6Cs9lt2sSy5f', 'kastamonu', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c6qj3G50HEpXcxxNSSab6amC2', 'kastamonu', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('crMMx8Q95YiXE3fnsNrm9FnnS', 'kastamonu', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cz09MsUFwsY1VAF6ILPbZ0ThS', 'sinop', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ci8jcqx4rqUchHsSsc33fiOLQ', 'sinop', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cxR1vd9aACal9sYBIApqQMzSc', 'sinop', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cBGl4IcIIQ9OiPKPMiTZ8q8ea', 'sinop', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cCNe8YgL8s1uQCRPzB5md2uRy', 'amasya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ckWG8ehlpeR48FRqfNuUEInmj', 'amasya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cZu6KCIeQkaY4d5vN9Yn7SujR', 'amasya', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cF03US0EOBYb8wXcE6rgqboal', 'amasya', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cQIzlQwImVlkuAnllkjyPZuud', 'tokat', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cRJ46ernCFBoPHlRx2Jyjy2Xv', 'tokat', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cbkLLedXR848FD4SYMuvBOkPX', 'tokat', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cQEXfh4tu4Ho6PEF2OWGz1f0m', 'tokat', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cVadQHgYXyCsyBbvgBN6hm7zo', 'yozgat', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cdW18zJBL3HQmjOUzG9RX3QkL', 'yozgat', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cFDvP6zgyaUKTZ6QCqEXQRxem', 'yozgat', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('ceWv1Ua5DdeTYiyY4vbaWhImQ', 'yozgat', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cOARAhFyHkkysRm2zxgFdT9Ks', 'nevsehir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cqBbXp9AdRJLjIsfVuYRkknX6', 'nevsehir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('ccbu5KjMdHjWT3Wh2ZSypbUPY', 'nevsehir', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c4IikAHwXfFNsbzsNbaUidVgJ', 'nevsehir', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c2btiLgvOgkDwxopLg7qG0cBj', 'nigde', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cIzN7oGMTgCg0TmjW2raWQwzG', 'nigde', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cSTkWZN2hiemyFf4Azg5j3cow', 'nigde', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c7kgLIJM3ENroql8Mfse2d0VB', 'nigde', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('ckGN84wAZ17pP31d2yjNJo347', 'aksaray', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ciFvz9HOzotchMPlP0Yk9tDEs', 'aksaray', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cHNhSTzc89ACyzD3LlBLp0Ca3', 'aksaray', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('c6Volwq6cYt8rrRHWru0csxeL', 'aksaray', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('cTvVYTtztLxH49y8DsF2LL9XK', 'karaman', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cDitTPnj9b9utnOwzMyr68Hlk', 'karaman', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cbuA0f3vYnIChJ2ie1hXNwLaf', 'karaman', 'Polipropilen Cami Halısı', 'polipropilen-cami-halisi', true, NOW(), NOW()),
  ('cCpcV8SVfGfw1fwBKfL2uE8zg', 'karaman', 'Polyamid Cami Halısı', 'polyamid-cami-halisi', true, NOW(), NOW()),
  ('c4c4zqwxLEUEWVnYpGN9xOYFI', 'agri', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ciGgLs7iFARPAQ7dgT8n3xuGl', 'agri', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cgbFxbWByL1FHvqj8b4Q9ILSi', 'ardahan', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ciMoeLGeTPAVhinR5qLqn3g90', 'ardahan', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c7k1rYFrvSE6wKrxYCfhpF5D5', 'bartin', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ceUKmdcz3TMVcWJ8EiJDRyW8g', 'bartin', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cLgSosljquAk2MeFZWB95nvoC', 'batman', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cgKRAIivV04ijjt9WyHOX5B1V', 'batman', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cB2GT3aJ4IcduSPOmGN23DgE9', 'bayburt', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cs04Q6h266MUb8nis4hlcZbJP', 'bayburt', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cqERvpb0pebjb1zHWUm3Ug3eZ', 'bilecik', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cRVL0Ei0wiBBUcPRMtHo7LzOz', 'bilecik', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cFzaIjn54Zv65DZ2la1HZqGSX', 'bingol', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c99zPvpWtgEVJOB8z5Uo8oBdh', 'bingol', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c6aAHwCocF65vmnhfQGnXtxVx', 'bitlis', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cZvdY9ReH4gPzS6DH6IHnMqpt', 'bitlis', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cySiRUm4CiV6mw7QTfjgWdkNM', 'burdur', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cG4m4JyQTudok0hiEj7bdvsJR', 'burdur', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('caAL1AOjIiadHBxKkjncVmTDT', 'corum', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cwIVpC3hBEW4lVK8dL8b4xOfJ', 'corum', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cqiRV8q6YpLLMK21PJVGRY7n7', 'duzce', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ckQ1InUaWfsfEB9MbyT5VMozD', 'duzce', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('crbd5IGA20bmCuhoQeICxZ3Q8', 'elazig', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cSPadrPBWJPFw4Le4ChqBloe4', 'elazig', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c3SL4J7b55xM4dAD8SmoaBLMJ', 'erzincan', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cQwYI8mRLZLe0vGLaDzB9a2nV', 'erzincan', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('csVljTqecul5InOQ7H1DsBfrF', 'gumushane', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cfSMLO7AHOyMgNM4Ab9sDqyVE', 'gumushane', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cf1VRfR5lqUwoOz6hBJZq7MVD', 'hakkari', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cNm8FCJWCEhWOcRgRoSnlfsm6', 'hakkari', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cI4vd4nGPYk6bkKiOlemFX80f', 'igdir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cv8n2zzLmD2ruWrRNCS18imU9', 'igdir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cXFDHoiEd2zsiUoP7EajBCMp5', 'karabuk', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cqv40d2rh9akdygiVhrJPNFgz', 'karabuk', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c3tVzte6PQ3bxVy30TZFqUDz0', 'kars', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c4L4DD76R5ugCyYCojsV1ldGO', 'kars', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cD5NmXdBlHooa5K1tc4FX2kHz', 'kilis', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cl64x1dnaASXfCKIkdbBnpL5E', 'kilis', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('czM8UYGNpxU1rfYlQb1wBb0Eh', 'kirsehir', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('ckLCEs15UjbQoXZuSbtdR65TF', 'kirsehir', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c7c9ULfwqUS7UtQPNcmiGXhqD', 'mardin', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cqES7OgzfrGxdiO7omyBU07g6', 'mardin', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c9vYXHIn1j4HgSvDdTs54ueIX', 'mus', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cTrkmHv7Qg6gGlymTcIovrsPp', 'mus', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c7jiPWHWuJZytZ3qS7PmxEKhK', 'osmaniye', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cKBB7oJ5nsPd2L7c2HRy0sSk4', 'osmaniye', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('ceQjvQQUZN8yet2kuK1WUhqZU', 'siirt', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cBuQ7w2mzOf5vGExRZNAoaMwB', 'siirt', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cnaospiWjqShUocJs8gBvx476', 'sirnak', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c4rVWaYccBhtqpVOYcV7hc2h7', 'sirnak', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cpX2f3TqlypgxKnSp3SU4rRhG', 'tunceli', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('c8oTB14cYePPfkJH59LNjIBqY', 'tunceli', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cB3zJfhjck0U0vTz8lPLLBAV5', 'usak', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cxcYzuM9lbiM41hR8w59xf5ll', 'usak', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cAfGMFq3ZG8oT5yUOVF15ACew', 'afyonkarahisar', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cEc4vSrMrWStvV12T0EVoritF', 'afyonkarahisar', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cKZ0VCzQgCmRYlBqPaUjkMf8D', 'denizli', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cxLI6JKlPmoB06wFuqEjnB2Ai', 'denizli', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('c3oyxuTyiDRI4SU1MGVIxuWNF', 'trabzon', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cSAbR303jBCVamf25948vG49u', 'trabzon', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW()),
  ('cb5QTMLlTn3Z2zQxQSILkLyGf', 'antalya', 'Akrilik Cami Halısı', 'akrilik-cami-halisi', true, NOW(), NOW()),
  ('cq06b6xjZtEoujCvxqratZmyQ', 'antalya', 'Yün Cami Halısı', 'yun-cami-halisi', true, NOW(), NOW())
ON CONFLICT ("citySlug", "keywordSlug") DO NOTHING;

-- ADIM 3: İç link haritası (Setting tablosu)
INSERT INTO "Setting" (id, key, value, "createdAt", "updatedAt")
VALUES ('cGj4P8nWi6uybS7xML890oPgN', 'internal_links', '{"akrilik cami halısı": "/kategori/akrilik-cami-halisi", "yün cami halısı": "/kategori/yun-cami-halisi", "polipropilen cami halısı": "/kategori/polipropilen-cami-halisi", "polyamid cami halısı": "/kategori/polyamid-cami-halisi", "axminster cami halısı": "/kategori/ozel-desen-axminster-cami-halisi", "özel desen cami halısı": "/kategori/ozel-desen-axminster-cami-halisi", "özel desen axminster": "/kategori/ozel-desen-axminster-cami-halisi", "saflı cami halısı": "/kategori/safli-akrilik-cami-halisi", "göbekli cami halısı": "/kategori/gobekli-akrilik-cami-halisi", "seccadeli cami halısı": "/kategori/seccadeli-akrilik-cami-halisi", "mihrap desenli cami halısı": "/kategori/gobekli-akrilik-cami-halisi", "göbek desenli cami halısı": "/kategori/gobekli-akrilik-cami-halisi", "keçe cami halısı altlığı": "/kategori/kece-cami-halisi-altligi", "kauçuk cami halısı altlığı": "/kategori/kaucuk-cami-halisi-altligi", "cami halısı altlığı": "/kategori/kece-cami-halisi-altligi", "cami halısı fiyatları": "/kategori/akrilik-cami-halisi", "cami halısı fiyatı": "/kategori/akrilik-cami-halisi", "cami halısı fiyat": "/kategori/akrilik-cami-halisi", "ucuz cami halısı": "/kategori/akrilik-cami-halisi", "ekonomik cami halısı": "/kategori/akrilik-cami-halisi", "kaliteli cami halısı": "/kategori/yun-cami-halisi", "cami halısı teklif": "/iletisim", "cami halısı siparişi": "/iletisim", "cami halısı montajı": "/iletisim", "cami halısı modelleri": "/", "cami halısı çeşitleri": "/", "cami halısı seçimi": "/sss", "cami halısı seçerken": "/sss", "cami halısı hesaplama": "/sss", "cami halısı ölçüleri": "/sss", "cami halısı teknik özellikleri": "/teknik-ozellikler", "sık sorulan sorular": "/sss", "antibakteriyel cami halısı": "/sss", "ısı yalıtımlı cami halısı": "/kategori/yun-cami-halisi", "neme dayanıklı cami halısı": "/kategori/polipropilen-cami-halisi", "alev almaz cami halısı": "/sss", "su geçirmez cami halısı": "/kategori/polipropilen-cami-halisi", "cami halısı bakımı": "/blog/bakim-plani-olmayan-cami-halilarinda-olusabilecek-riskler", "cami halısı temizliği": "/blog/bakim-plani-olmayan-cami-halilarinda-olusabilecek-riskler", "cami halısı yıkama": "/blog/bakim-plani-olmayan-cami-halilarinda-olusabilecek-riskler", "cami halısı yıpranma": "/blog/yanlis-teknik-secim-neden-hali-yipratiyor", "yanlış teknik seçim": "/blog/yanlis-teknik-secim-neden-hali-yipratiyor", "zemin analizi": "/blog/eksik-zemin-analizi-cami-halisini-nasil-etkiler", "cami halısı montaj": "/blog/kalitesiz-montaj-sureci-hali-omrunu-kisaltiyor", "akrilik mi yün mü": "/karsilastirma/akrilik-vs-yun-cami-halisi", "akrilik vs yün": "/karsilastirma/akrilik-vs-yun-cami-halisi", "polipropilen vs polyamid": "/karsilastirma/polipropilen-vs-polyamid-cami-halisi", "saflı mı göbekli mi": "/karsilastirma/safli-vs-gobekli-vs-seccadeli", "cami halısı karşılaştırma": "/karsilastirma", "istanbul cami halısı": "/cami-halisi/istanbul", "ankara cami halısı": "/cami-halisi/ankara", "izmir cami halısı": "/cami-halisi/izmir", "bursa cami halısı": "/cami-halisi/bursa", "antalya cami halısı": "/cami-halisi/antalya", "konya cami halısı": "/cami-halisi/konya", "kayseri cami halısı": "/cami-halisi/kayseri", "adana cami halısı": "/cami-halisi/adana", "gaziantep cami halısı": "/cami-halisi/gaziantep", "trabzon cami halısı": "/cami-halisi/trabzon", "samsun cami halısı": "/cami-halisi/samsun", "kocaeli cami halısı": "/cami-halisi/kocaeli", "diyarbakır cami halısı": "/cami-halisi/diyarbakir", "eskişehir cami halısı": "/cami-halisi/eskisehir", "mersin cami halısı": "/cami-halisi/mersin", "şanlıurfa cami halısı": "/cami-halisi/sanliurfa", "denizli cami halısı": "/cami-halisi/denizli", "malatya cami halısı": "/cami-halisi/malatya", "hatay cami halısı": "/cami-halisi/hatay", "manisa cami halısı": "/cami-halisi/manisa"}', NOW(), NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, "updatedAt" = NOW();

-- Tamamlandı! Toplam:
-- • 78 şehir kaydı
-- • 302 keyword sayfası
-- • 69 iç link haritası girişi